export const products = [
  {
    id: 1,
    name: "Eternal Youth",
    route: "eternal-youth-serum",
    description:
      "A luxury serum enriched with vitamins C and E to restore your skin's natural glow.",
    category: "Serum",
    price: 169,
    stock: 1120,
    image: "/3.png",
    rating: 4.8,
    tags: ["Glow", "Anti-Aging", "Hydrating"],
  },
  {
    id: 2,
    name: "Silken Touch",
    route: "silken-touch-moisturizer",
    description:
      "A deeply hydrating moisturizer with hyaluronic acid and shea butter.",
    category: "Moisturizer",
    price: 159,
    stock: 185,
    image: "/2.png",
    rating: 4.7,
    tags: ["Hydrating", "Nourishing"],
  },
  {
    id: 3,
    name: "Pure Bliss",
    route: "pure-bliss-cleanser",
    description:
      "A gentle cleansing balm that removes makeup and impurities while nourishing the skin.",
    category: "Cleanser",
    price: 139,
    stock: 1150,
    image: "/1.png",
    rating: 4.6,
    tags: ["Gentle", "Makeup Remover", "Hydrating"],
  },
  {
    id: 4,
    name: "Radiance Revival",
    route: "radiance-revival-eye-care",
    description:
      "A rejuvenating eye cream to reduce puffiness and diminish fine lines.",
    category: "Eye Care",
    price: 249,
    stock: 1100,
    image: "/4.png",
    rating: 4.9,
    tags: ["Anti-Aging", "Brightening", "Soothing"],
  },
  {
    id: 5,
    name: "Velvet Veil",
    route: "velvet-veil-night-care",
    description:
      "A restorative night cream that works overnight to repair and hydrate your skin.",
    category: "Night Care",
    price: 379,
    stock: 170,
    image: "/6.png",
    rating: 4.7,
    tags: ["Repairing", "Hydrating", "Anti-Aging"],
  },
  {
    id: 6,
    name: "GlowShield SPF7",
    route: "glowShield-spf7-sunscreen",
    description:
      "A lightweight sunscreen offering broad-spectrum protection with a matte finish.",
    category: "Sunscreen",
    price: 134,
    stock: 2100,
    image: "/5.png",
    rating: 4.5,
    tags: ["Sun Protection", "Lightweight", "Non-Greasy"],
  },
  {
    id: 7,
    name: "Luminous Elixir",
    route: "luminous-elixir-facial-oil",
    description:
      "A nourishing facial oil with rosehip and jojoba to replenish dry, tired skin.",
    category: "Facial Oil",
    price: 189,
    stock: 95,
    image: "/14.png",
    rating: 4.8,
    tags: ["Nourishing", "Replenishing", "Glow"],
  },
  {
    id: 8,
    name: "Crystal Clear",
    route: "crystal-clear-exfoliator",
    description:
      "A gentle enzymatic exfoliator that removes dead skin cells without irritation.",
    category: "Exfoliator",
    price: 145,
    stock: 320,
    image: "/15.png",
    rating: 4.6,
    tags: ["Exfoliating", "Gentle", "Brightening"],
  },
  {
    id: 9,
    name: "Timeless Beauty",
    route: "timeless-beauty-mask",
    description:
      "A rejuvenating mask with peptides and collagen to restore skin elasticity and firmness.",
    category: "Mask",
    price: 199,
    stock: 210,
    image: "/16.png",
    rating: 4.9,
    tags: ["Anti-Aging", "Firming", "Rejuvenating"],
  },
  {
    id: 10,
    name: "Morning Dew",
    route: "morning-dew-toner",
    description:
      "A hydrating toner with rose water and aloe vera to balance skin pH and prepare for serums.",
    category: "Toner",
    price: 129,
    stock: 480,
    image: "/10.png",
    rating: 4.7,
    tags: ["Balancing", "Hydrating", "Soothing"],
  },
  {
    id: 11,
    name: "Porcelain Perfection",
    route: "porcelain-perfection-foundation",
    description:
      "A lightweight foundation with skincare benefits, offering medium coverage with a natural finish.",
    category: "Makeup",
    price: 165,
    stock: 390,
    image: "/11.webp",
    rating: 4.5,
    tags: ["Lightweight", "Natural", "Skincare Infused"],
  },
  {
    id: 12,
    name: "Azure Dreams",
    route: "azure-dreams-lip-treatment",
    description:
      "A luxurious lip treatment that repairs, plumps, and softens with shea butter and peptides.",
    category: "Lip Care",
    price: 110,
    stock: 560,
    image: "/12.png",
    rating: 4.8,
    tags: ["Plumping", "Repairing", "Hydrating"],
  },
  {
    id: 13,
    name: "Miracle Worker",
    route: "miracle-worker-spot-treatment",
    description:
      "A targeted treatment formulated with salicylic acid and tea tree to clear blemishes overnight.",
    category: "Treatment",
    price: 155,
    stock: 275,
    image: "/13.png",
    rating: 4.7,
    tags: ["Clarifying", "Targeted", "Soothing"],
  },
  {
    id: 14,
    name: "Celestial Glow",
    route: "celestial-glow-highlighter",
    description:
      "A cream highlighter infused with light-reflecting particles for a supernatural radiance.",
    category: "Makeup",
    price: 145,
    stock: 310,
    image: "/7.png",
    rating: 4.6,
    tags: ["Radiant", "Cream", "Luminous"],
  },
  {
    id: 15,
    name: "Divine Essence",
    route: "divine-essence-perfume",
    description:
      "A sophisticated fragrance with notes of jasmine, sandalwood, and vanilla for an unforgettable presence.",
    category: "Fragrance",
    price: 225,
    stock: 180,
    image: "/8.png",
    rating: 4.9,
    tags: ["Floral", "Woody", "Long-lasting"],
  },
  {
    id: 16,
    name: "Silk Caress",
    route: "silk-caress-body-lotion",
    description:
      "A luxurious body lotion with silk proteins and shea butter for velvet-soft skin.",
    category: "Body Care",
    price: 140,
    stock: 420,
    image: "/9.png",
    rating: 4.7,
    tags: ["Moisturizing", "Silky", "Nourishing"],
  },
  {
    id: 17,
    name: "Petal Soft",
    route: "petal-soft-hand-cream",
    description:
      "An intensive hand treatment with ceramides and vitamin E to repair and protect dry hands.",
    category: "Hand Care",
    price: 89,
    stock: 640,
    image: "/17.jpg",
    rating: 4.8,
    tags: ["Repairing", "Protective", "Non-greasy"],
  },
  {
    id: 18,
    name: "Ocean Mineral",
    route: "ocean-mineral-body-scrub",
    description:
      "A revitalizing body scrub with sea salt and algae extract to exfoliate and detoxify.",
    category: "Body Care",
    price: 120,
    stock: 350,
    image: "/18.jpg",
    rating: 4.6,
    tags: ["Exfoliating", "Detoxifying", "Invigorating"],
  },
  {
    id: 19,
    name: "Midnight Repair",
    route: "midnight-repair-neck-cream",
    description:
      "A specialized cream targeting the delicate neck area with peptides and retinol.",
    category: "Neck Care",
    price: 195,
    stock: 140,
    image: "/19.jpg",
    rating: 4.8,
    tags: ["Firming", "Anti-Aging", "Specialized"],
  },
  {
    id: 20,
    name: "Golden Hour",
    route: "golden-hour-bronzing-oil",
    description:
      "A subtle bronzing oil that adds a sun-kissed glow while nourishing the skin.",
    category: "Body Care",
    price: 135,
    stock: 270,
    image: "/20.jpg",
    rating: 4.7,
    tags: ["Bronzing", "Illuminating", "Hydrating"],
  }
];
